### PR TITLE
Reworked sources to ES6

### PR DESCRIPTION
**Pull request by havenchyk**
Hi @roman01la, I'm not an expert in ES6, but I tried, so if you have time to review this patch, it would be really great!

Please, do not hesitate to leave comments on the changes, I will be happy to fix any issues.

### CODE REVIEW

**Comment by havenchyk** [comment]
phew, tests are green finally.

**Comment by havenchyk** [comment]
@roman01la, sorry, pushed latest changes with `--force`, so all your comments are gone. Should be fixed.

**Comment by roman01la** [comment]
@havenchyk No problem. And thank you for so much work! I'm going to review the code itself.

**Comment by havenchyk** [comment]
@roman01la you're welcome. Feel free to ask to change anything in the sources to more readable way.

**Pull request closed without merging**
